config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [] do
    resources :bookings, only: [:index]
  end
  
  get 'my_cars', to: 'cars#my_cars'

  resources :cars do
    resources :bookings, only: %i[index new create]
  end

  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
  validates :starts_at, presence: true
  validates :ends_at, presence: true

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, presence: true, numericality: true
  validates :price_per_day, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @bookings = @user.bookings
    @prices = @bookings.map do |booking|
      start_date = booking.starts_at
      end_date = booking.ends_at
      car = booking.car
      price = calculate_price(start_date, end_date, car)
      days = (end_date - start_date).to_i
      [price, days]
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @start_date = @booking.starts_at
    @end_date = @booking.ends_at
    @car = @booking.car
    @price = calculate_price(@start_date, @end_date, @car)
    @date = (@end_date - @start_date).to_i
  end

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    @booking.car = @car
    return unless params[:starts_date] && params[:ends_date]

    @booking.starts_at = Date.strptime(params[:booking][:starts_at], "%Y-%m-%d")
    @booking.ends_at = Date.strptime(params[:booking][:ends_at], "%Y-%m-%d")
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.accepted = false
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to user_bookings_path(current_user), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user), notice: 'Booking was successfully destroyed.'

  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :car_id)
  end

  def calculate_price(starts_at, ends_at, car)
    (ends_at.to_date - starts_at.to_date).to_i * car.price_per_day
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_search_params_and_dates, only: [:index]

  def index
    @cars = Car.all
    @booking = Booking.new

    return unless params[:search]

    @search_params = search_params.to_h
    if @search_params[:starts_date]
      @search_params[:starts_date], @search_params[:ends_date] = @search_params[:starts_date].split(' to ')
    end

    @cars = @cars.where(city: @search_params[:city]) if @search_params[:city].present?
    @cars = @cars.where(model: @search_params[:model]) if @search_params[:model].present?
    @cars = @cars.where(brand: @search_params[:brand]) if @search_params[:brand].present?
    session[:search] = @search_params
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @start_date = params[:start_date] || session[:search][:starts_date]
    @end_date = params[:end_date] || session[:search][:ends_date]
    @search_params = params[:search] || {}
  end
  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to my_cars_path
  end

  def my_cars
    if user_signed_in?
      @my_cars = current_user.cars || []
    else
      redirect_to new_user_session_path
    end
  end

  private

  def set_search_params_and_dates
    return unless params[:search]

    @search_params = search_params.to_h
    if @search_params[:start_date]
      start_date, end_date = @search_params[:start_date].split(' to ')
      @search_params[:starts_date] = Date.strptime(start_date, "%d-%m-%Y") if start_date
      @search_params[:ends_date] = Date.strptime(end_date, "%d-%m-%Y") if end_date
      @start_date = @search_params[:starts_date]
      @end_date = @search_params[:ends_date]
    end
    session[:search] = @search_params
  end

  def search_params
    params.require(:search).permit(:city, :model, :brand, :start_date)
  end

  def car_params
    params.require(:car).permit(:brand, :model, :year_of_production, :address, :price_per_day, :city, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cars = Car.where.not(user: current_user).order("created_at").limit(3)
    @my_cars = current_user ? current_user.cars : []
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="container persocontainer">
<div class="voiture">
  <% @bookings.reverse.each do |booking| %>
    <div class="card">
      <div class="card-img">
        <%= cl_image_tag booking.car.photo.key, class: "card-img", width: '226', height: '150.66' if booking.car.photo.present? %>
      </div>
      <div class="card-title"><%= booking.car.brand %> <%= booking.car.model %></div>
      <div class="card-subtitle", style="gap: 10px">
        <p style="width: 70px;">Start date: <%= booking.starts_at %></p>
        <p style= "width: 70px;">End date: <%= booking.ends_at %></p></div>

      <div class="card-footer">

      <div class="card-subtitle" style="text-align: center;">
          Total price in $: <%= booking.car.price_per_day * (booking.ends_at.to_date - booking.starts_at.to_date).to_i %>
          <p>Number of days: <%= (booking.ends_at.to_date - booking.starts_at.to_date).to_i %></p>
        </div>
        </div>


        <% if (booking.ends_at.to_date - booking.starts_at.to_date).to_i != 0 %>
          <div style="text-align: center; padding:10px">
            <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete } , method: :delete, class: "card-btn persobtn" %>
            </div>
        <% end %>
        <div style="text-align: center;padding:10px">
<% if !booking.accepted %>
            <p style="color: orange;">Status: Pending</p>
            <% else %>
            <p>Status: Accepted</p>
            <% end %>
        </div>

      </div>
      <% end %>
    </div>

</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/cars/index.html.erb
<div class="container", style="align-items: center;
    display: flex;
    justify-content: center;">
  <%= render 'pages/search'%>
</div>

<div class="grid-container">
  <% @cars.each do |car| %>
    <div class="card">
      <div class="card-img">
        <%= cl_image_tag car.photo.key, class: "card-img", width: '226', height: '150.66' if car.photo.present? %>
      </div>
      <div class="card-title"><%= car.brand %> <%= car.model %></div>
      <div class="card-subtitle"><%= car.address %></div>
      <div class="card-footer">
        <%= simple_form_for @booking, url: car_bookings_path(car_id: car.id), method: :post, html: { class: "card-btn" } do |f| %>
  <%= f.hidden_field :starts_at, value: @start_date %>
  <%= f.hidden_field :ends_at, value: @end_date %>
  <%= f.button :submit, '', id: 'submit-button', style: 'display:none' %>
  <label for="submit-button" class="card-price"><%= car.price_per_day %><span>€/par jour</span></label>
<% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/my_car.html.erb
<% @my_cars.each do |car| %>
  <div>
    <h2><%= car.brand %> <%= car.model %></h2>
    <p><%= car.address %></p>
    <p><%= car.price_per_day %> €/par jour</p>
  </div>
<% end %>

app/views/cars/my_cars.html.erb
<div class="container">
  <% if @my_cars %>
    <div class="row" style="display: flex; justify-content: center; flex-wrap: wrap;">
      <% @my_cars.each_slice(3) do |cars_group| %>
        <% cars_group.each do |car| %>
          <div class="voiture" style="flex: 0 0 33.33%; max-width: 33.33%;">
          <div class="card">
            <div class="card-img">
              <%= cl_image_tag car.photo.key, class: "card-img", width: '226', height: '150.66' if car.photo.present? %>
            </div>
            <div class="card-title"><%= car.brand %> <%= car.model %></div>
            <div class="card-subtitle" style="gap: 10px">
              <p style="width: 155px;">Address: <%= car.address %></p>
              <p style="width: 155px;">Price per day: <%= car.price_per_day %> €</p>
            </div>
            <div class="card-footer">
              <div class="card-subtitle" style="text-align: center; display: block;">
                <p style="color: <%= car.bookings.count != 0 ? 'green' : 'red' %>; font-weight: <%= car.bookings.count != 0 ? '600' : 'normal' %>;">Number of bookings: <%= car.bookings.count %></p>
              </div>

            </div>
            <div style="text-align: center; padding:10px; display: block;">
                <%= link_to "Delete", car_path(car), data: { turbo_method: :delete } , method: :delete, class: "card-btn persobtn" %>
              </div>
             </div>
       </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<div class="custom-container">
  <%= simple_form_for @car, html: { multipart: true } do |f| %>
    <%= f.input :brand, label: 'Brand' %>
    <%= f.input :model, label: 'Model' %>
    <%= f.input :year_of_production, label: 'Year of Production' %>
    <%= f.input :address, label: 'Address' %>
    <%= f.input :price_per_day, label: 'Price per Day' %>
    <%= f.input :city, label: 'City' %>
    <%= f.input :photo, as: :file, label: 'Photo' %>
    <%= f.button :submit, 'List for Rent' %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container", style="align-items: center;
    display: flex;
    justify-content: center;">
  <%= render 'pages/search'%>
</div>

<div class="grid-container">
  <div class="card">
    <div class="card-img">
      <%= cl_image_tag @car.photo.key, class: "card-img", width: '226', height: '150.66' if @car.photo.present? %>
    </div>
    <div class="card-title"><%= @car.brand %> <%= @car.model %></div>
    <div class="card-subtitle"><%= @car.address %></div>
    <div class="card-footer">
       <% debugger %>
      <%= simple_form_for @booking, url: car_bookings_path(car_id: @car.id), method: :post, html: { class: "card-btn" } do |f| %>
        <%= f.hidden_field :starts_at, value: @start_date %>
        <%= f.hidden_field :ends_at, value: @end_date %>

        <%= f.button :submit, '', id: "submit-button-#{@car.id}", style: 'display:none' %>

        <label for="submit-button" class="card-price"><%= @car.price_per_day %><span>€/par jour</span></label>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="shortcut icon" type="image/png" href="<%= asset_path('rentalsmall.png') %>"/>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="text-center" >
  <!-- Grid container -->
  <div class="container" style="display:flex; align-content:center; justify-content:center;">

    <section class="">
      <h2 class="title">Rental</h2>
      <p class="text">Rental is a car rental platform that offers a wide range of vehicles for every need. Whether you're looking for a compact car for city cruising or an SUV for family outings, we have quality options available for you. Our user-friendly interface makes it easy to explore, select, and drive with ease. Experience competitive pricing and full transparency with us, ensuring no surprises or hidden fees. Book confidently and get the best value for your rental with Rental.</p>
    </section>

  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 " style="align-items: center;
    position: relative;
    display: flex;
    justify-content: center;
    color: white ;">
    © 2024 Copyright:
    <a class="link" href="https://github.com/Bnoure">By Nour-Eddine Benkerroum </a>
  </div>
  <div class="logo">
  <%= link_to '#herotext' do %>
    <%= image_tag("Rental.png", class: "logo") %>
  <% end %>
</div>
  <!-- Copyright -->
</footer>

app/views/pages/_search.html.erb
<div class="container">
<div class="search">
    <%= simple_form_for :search, url: cars_path, method: :get, html: { class: "fomrme", id: "search-form", onsubmit: "return validateForm();" } do |f| %>
  <div class="row lasearch">
    <div class="col-md-3">
      <%= f.input :city, label: "City", collection: Car.pluck(:city).uniq, input_html: { id: "city-input", class: "form-control" }, name: 'search[city]' %>
    </div>
    <div class="col-md-3">
  <%= f.input :model, collection: Car.pluck(:model).uniq, label: "Model", input_html: { id: "model-input", class: "form-control select" } %>
</div>
    <div class="col-md-3">
      <%= f.input :brand, collection: Car.pluck(:brand).uniq, label: "Brand", input_html: { id: "brand-input", class: "form-control select" } %>
    </div>
    <div class="col-md-3">
      <%= f.input :start_date, label: "Booking date ", input_html: { id: "start-date-input", class: "form-control", placeholder: "Dates you are looking for ", type: "text", data: { controller: "flatpickr" } } %>
    </div>
    <div class="col-md-3 maclassebut">
      <div id="date-difference"></div>
      <%= f.button :submit, "Search", class: "monbutton" %>
    </div>
    <%= f.input :end_date, as: :hidden, input_html: { id: "end-date-input" } %>
  </div>

<% end %>
<h2 class = "now">Rental now</h2>
  </div>

</div>

app/views/pages/home.html.erb
<div class="container", style="gap: 66px;">
  <div class="imaghero">
    <%= image_tag("img.png", class: "imb") %>
  </div>
  <div class="herotext">
    <h1 class="headline">Get the car that you want easily
    <p class="subtitre"> Driven by a mission rooted in collaborative and responsible consumption
    </p>
    <div class="subcontent">
      <button class="buttonaccueil">
    <%= link_to 'Find the perfect car for you', '#search-section', style: "color:white !important"%>
      </button>
      <p class ="accroche">5,000 people already satisfied by Rental </p>

    </div>
  </div>



</div>

<div class="feature">
  <div class="contentfeature">
    <div class="feature-block">
      <%= image_tag("iconetel.png", class: "imgfeature") %>
      <div class="feature-text">
        <h3 class="titlefeature">User-Friendly Interface</h3>
        <p class="subfeature">Our car rental website offers a user-friendly interface, ensuring easy navigation and quick vehicle selection. With its intuitive design, finding and booking cars is effortless.</p>
      </div>
    </div>
    <div class="feature-block">
      <%= image_tag("iconevoiture.png", class: "imgfeature") %>
      <div class="feature-text">
        <h3 class="titlefeature">Wide Range of Vehicles</h3>
        <p class="subfeature">Explore our diverse selection of vehicles tailored to meet every need. Whether it's a compact car for city cruising or an SUV for family outings, we provide quality options, all meticulously maintained and ready to roll.</p>
      </div>
    </div>
    <div class="feature-block">
      <%= image_tag("iconebalance.png", class: "imgfeature") %>
      <div class="feature-text">
        <h3 class="titlefeature">Rates and Transparency</h3>
        <p class="subfeature">Experience competitive pricing and full transparency with us. Our clear, accurate pricing and up-to-date offers ensure no surprises or hidden fees, allowing you to book confidently and get the best value for your rental.</p>
      </div>
    </div>
  </div>
</div>



<div id="search-section">
  <%= render 'search' %>
</div>
<div class="grid-container">
  <div class="explorer">
    <%= image_tag("fusee.png", class:"fusee")%>
    <h2 class="bottomtext">Explore, Select, and Drive with Ease on Our User-Friendly Car Rental Platform!</h2>
  </div>

   <div class="voiture">
      <% @cars.each do |car| %>
    <div class="card">
      <div class="card-img">
          <%= cl_image_tag car.photo.key, class: "card-img", width: '226', height: '150.66' if car.photo.present? %>

      </div>
      <div class="card-title"><%= car.brand %> <%= car.model %></div>
      <div class="card-subtitle"><%= car.address %></div>

      <div class="card-footer">
        <%= link_to car_path(car), class: "card-btn" do %>
          <div class="card-price"><%= car.price_per_day %><span>€/par jour</span> </div>
        <% end %>
      </div>
    </div>
  <% end %>
   </div>

</div>
<%= render 'footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
            <!-- ... -->
            <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
              <div class="container-fluid">
                <%= link_to root_path, class: "navbar-brand" do %>
                  <%= image_tag "Rental.png" %>
                <% end %>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto">
                    <% if user_signed_in? %>
                      <li class="nav-item active"></li>
                      <div class="centerlink">
                        <%= link_to "Your Bookings", user_bookings_path(current_user), class: "nav-link" %>
                        <%= link_to "You Car in rent", my_cars_path, class: "nav-link" %>
                        <%= link_to "Rent your car", new_car_path, class: "nav-link" %>
                      </div>
                      <div class="about" data-controller="modal">
                        <li>
                          <button class="nav-link" style="font-weight:600 ;background: none; padding-right: 20px; font-size: 18px; margin-top: 20px;border: none" data-action="click->modal#open">About </button>
                          <dialog id="dialog" data-modal-target="dialog">
                            <div class="modal-content">
                              <% if $image_url.nil? %>
                                <%= image_tag 'nour.jpg', class: "avatarNour" %>
                              <% else %>
                                <%= cl_image_tag($image_url, class: "avatarNour") %>
                              <% end %>
                              <h3 style="display: flex; align-items: center; justify-content: center;">👋 Hey, je suis Nour-Eddine Benkerroum</h3>
                              <p>🚀 Passionné par le développement web, Je poursuis ma passion pour le développement web après avoir complété ma formation chez Le Wagon, me préparant à embrasser pleinement la carrière de développeur full stack. Fort d'une expérience antérieure en tant que chef de projet IT, j'ai décidé de changer de cap pour embrasser pleinement le monde du développement. Mon objectif est d'acquérir une expertise solide dans l'écosystème JavaScript, en me concentrant sur React, TypeScript, Node.js, et plus encore.</p>
                              <hr>
                              <h4>🌱 Ce que j'apprends actuellement</h4>
                              <ul>
                                <li>JavaScript: Découverte des fondamentaux et des concepts avancés pour des applications interactives.</li>
                                <li>React: Immersion dans la création d'interfaces utilisateur dynamiques et réactives.</li>
                                <li>TypeScript: Apprentissage de ce langage pour renforcer la qualité et la maintenabilité du code.</li>
                                <li>Node.js: Exploration de l'environnement serveur pour développer des applications web complètes.</li>
                              </ul>
                              <hr>
                              <h4>🎯 Mes intérêts</h4>
                              <ul>
                                <li>Développement Full Stack: Aspirer à devenir un développeur versatile capable de travailler à la fois sur le front-end et le back-end.</li>
                                <li>Ecosystème JavaScript: Se spécialiser dans l'écosystème JS pour créer des applications modernes et performantes.</li>
                                <li>Ruby on Rails: Approfondir mes connaissances et compétences en Ruby on Rails pour développer des applications web dynamiques et évolutives.</li>
                                <li>Apprentissage Continu: Reste à l'affût des dernières technologies et meilleures pratiques en développement web.</li>
                              </ul>
                              <hr>
                              <h4>📫 Me contacter</h4>
                              <ul>
                                <li><a href="mailto:noureddine.benkerroum@gmail.com">Mail</a></li>
                                <li><a href="https://www.linkedin.com/in/nbenkerroum/">Linkedin</a></li>
                              </ul>
                              <button data-action="click->modal#close" data-modal-target="x" aria-label="close" class="x">❌</button>
                            </div>
                          </dialog>
                        </li>
                        <!-- ... -->
                      </div>
                      <li class="nav-item dropdown">
                        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <% if current_user.avatar.attached? %>
                            <%= cl_image_tag current_user.avatar.key, class: "avatar", alt: "dropdown menu" %>
                          <% else %>
                            <%= image_tag "https://i.pravatar.cc/300", class: "avatar", alt: "dropdown menu" %>
                          <% end %>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                          <%#= link_to "Action", "#", class: "dropdown-item" %>
                          <%#= link_to "Another action", "#", class: "dropdown-item" %>
                          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
                        </div>
                      </li>
                    <% else %>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size: larger">
                          <span style="font-size: 10px"> </span>Connexion
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <%= form_for(User.new, url: user_session_path) do |f| %>
                            <div class="mb-3">
                              <%= f.label :email, class: "form-label", style: "font-size: larger" %>
                              <%= f.email_field :email, class: "form-control", style: "width: 190%;" %>
                            </div>
                            <div class="mb-3">
                              <%= f.label :password, class: "form-label", style: "font-size: larger" %>
                              <%= f.password_field :password, class: "form-control", style: "width: 190%;" %>
                            </div>
                            <%= f.submit "Se connecter", class: "custom-button", style: "margin-left: 68%; height: 22%; width: 77%;" %>
                          <% end %>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>